### ISSUE TITLE
Issue with Bar3d

### ISSUE THREAD

**Issue by badnaam** [pullmonkey/open_flash_chart#7]
The following json should show two 3d bars (Energy and Water Efficient) with values 253, 400 and 48, 400. But I see two bars labelled (Energey and Water Efficieny, which is correct), with values 253,48 and 400,400.

Is my assumption correct or is this json being rendered incorrectly?

{"title":{"text":"Eco points by category"},"colours":"#38E081","elements":[{"text":"Energy","colours":"#38E081","font-size":3,"type":"bar_3d","values":[253,400],"grid-colour":"#000000"},{"text":"Water Efficieny","colours":"#38E081","font-size":3,"type":"bar_3d","values":[48,400],"grid-colour":"#000000"}],"y_axis":{"steps":100,"max":500,"min":0},"grid-colour":"#000000","bg_colour":"#ffffff","x_axis":{"labels":{"labels":["Energy","Water Efficieny"]}}}

**Comment by pullmonkey** [comment]
Look at what this produces:
{"title":{"text":"Eco points by category"},"colours":"#38E081","elements":[{"text":"Energy","colour":"#38E081","font-size":12,"type":"bar_3d","values":[253,400],"grid-colour":"#000000"},{"text":"Water Efficiency","colour":"#9a89f9","font-size":12,"type":"bar_3d","values":[48,400],"grid-colour":"#000000"}],"y_axis":{"steps":100,"max":500,"min":0},"grid-colour":"#000000","bg_colour":"#ffffff","x_axis":{"labels":{"labels":["Day 1","Day 2"]}}}

You are creating two series, one for Energy and one for Water.  
I changed the colors for the graphs, so you can see the association.
I made the font bigger for the series labels so you see that they are the right values for the right association.
And I changed the lables for the X-Axis since that would definitely be confusing.

I hope this helps clear up some confusion, let me know otherwise.
- Charlie

**Comment by badnaam** [comment]
Thanks!  I see whats happening now. Resolved!
